---
- include_vars:
    file: defaults/main.yml
- include_vars:
    file: vars/main.yml
- name: Load distribution variables
  include_vars:
    file: vars/{{ ansible_os_family }}.yml
- include: fdio_vpp-install.yml
